export const FETCH_FORECAST_REQUEST = "FETCH_FORECAST_REQUEST";
export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS";
export const FETCH_FORECAST_FAILURE = "FETCH_FORECAST_FAILURE";

export const GET_DAILY_DETAILS_BY_DATE = "GET_DAILY_DETAILS_BY_DATE";
export const CHANGE_LOCATION = "CHANGE_LOCATION";
